// app/layout.tsx
import type {Metadata} from 'next';
import {ReactNode} from "react";
import {store} from "@/store";
import Providers from "./Providers";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode;
}) {
    return (
        <Providers>
        <html lang="en">
        <body>
        {children}
        </body>
        </html>
        </Providers>
    );
}
